### ISSUE TITLE
Insecure Password Storage

### ISSUE THREAD

**Issue by VinVorteX** [isatyamks/CodeCash#13]
Issue: User passwords are currently stored in plain text in the MongoDB database. This is a major security vulnerability, as plain text passwords can be easily exposed in the event of a data breach.

Issue: User passwords are currently stored in plain text in the MongoDB database. This is a major security vulnerability, as plain text passwords can be easily exposed in the event of a data breach.

**Comment by VinVorteX** [comment]
hey @isatyamks I would like to work on this issue

**Comment by isatyamks** [comment]
@VinVorteX The app is currently in the development phase and hasn't been deployed yet, so it's not a major concern at the moment.

**Comment by VinVorteX** [comment]
Yes

**Comment by VinVorteX** [comment]
Please assign me other issues I created
